import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import util.Validaciones;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Marcos 2026
 */
public class frmMedicamentos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmMedicamentos.class.getName());

    /**
     * Creates new form frmMedicamentos
     */
    public frmMedicamentos() {
        initComponents();
        Validaciones.soloNumeros(txtCodigo);
        Validaciones.soloLetras(txtNombre);
        Validaciones.soloLetras(txtTipo);
        Validaciones.soloNumeros(txtPrecio);
        Validaciones.soloNumeros(txtStock);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Código:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Tipo:");

        jLabel4.setText("Precio:");

        jLabel5.setText("Stock:");

        txtNombre.addActionListener(this::txtNombreActionPerformed);

        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txtStock)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(txtNombre)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistrar)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnModificar)
                            .addComponent(btnEliminar)))
                    .addComponent(btnBuscar))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRegistrar)
                                .addGap(63, 63, 63))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(btnEliminar)))
                .addContainerGap(157, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
String codigo = txtCodigo.getText().trim();
String nombre = txtNombre.getText().trim();
String tipo = txtTipo.getText().trim();
String precio = txtPrecio.getText().trim();
String stock = txtStock.getText().trim();

if (codigo.isEmpty() || nombre.isEmpty() || tipo.isEmpty() || precio.isEmpty() || stock.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Por favor complete todos los campos.");
    return;
}

try (FileWriter fw = new FileWriter("medicamentos.txt", true);
     BufferedWriter bw = new BufferedWriter(fw);
     PrintWriter pw = new PrintWriter(bw)) {

    pw.println(codigo + "," + nombre + "," + tipo + "," + precio + "," + stock);
    JOptionPane.showMessageDialog(this, "Medicamento registrado con éxito.");

    txtCodigo.setText("");
    txtNombre.setText("");
    txtTipo.setText("");
    txtPrecio.setText("");
    txtStock.setText("");

} catch (IOException e) {
    JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
String codigoBuscado = txtCodigo.getText().trim();

if (codigoBuscado.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Ingrese el código del medicamento a buscar.");
    return;
}

File archivo = new File("medicamentos.txt");
if (!archivo.exists()) {
    JOptionPane.showMessageDialog(this, "No hay medicamentos registrados aún.");
    return;
}

boolean encontrado = false;
try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
    String linea;
    while ((linea = br.readLine()) != null) {
        String[] datos = linea.split(",");
        if (datos.length >= 5 && datos[0].trim().equalsIgnoreCase(codigoBuscado)) {
            txtNombre.setText(datos[1]);
            txtTipo.setText(datos[2]);
            txtPrecio.setText(datos[3]);
            txtStock.setText(datos[4]);
            JOptionPane.showMessageDialog(this, "Medicamento encontrado.");
            encontrado = true;
            break;
        }
    }
    if (!encontrado) {
        JOptionPane.showMessageDialog(this, "Medicamento no encontrado.");
    }
} catch (IOException e) {
    JOptionPane.showMessageDialog(this, "Error al buscar: " + e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
String codigo = txtCodigo.getText().trim();
String nombre = txtNombre.getText().trim();
String tipo = txtTipo.getText().trim();
String precio = txtPrecio.getText().trim();
String stock = txtStock.getText().trim();

if (codigo.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Ingrese el código del medicamento a modificar.");
    return;
}

File archivo = new File("medicamentos.txt");
if (!archivo.exists()) {
    JOptionPane.showMessageDialog(this, "El archivo no existe.");
    return;
}

List<String> lineas = new ArrayList<>();
boolean modificado = false;

try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
    String linea;
    while ((linea = br.readLine()) != null) {
        String[] datos = linea.split(",");
        if (datos.length >= 5 && datos[0].trim().equalsIgnoreCase(codigo)) {
            lineas.add(codigo + "," + nombre + "," + tipo + "," + precio + "," + stock);
            modificado = true;
        } else {
            lineas.add(linea);
        }
    }
} catch (IOException e) {
    JOptionPane.showMessageDialog(this, "Error al leer: " + e.getMessage());
    return;
}

if (modificado) {
    try (PrintWriter pw = new PrintWriter(new FileWriter(archivo, false))) {
        for (String l : lineas) {
            pw.println(l);
        }
        JOptionPane.showMessageDialog(this, "Medicamento modificado con éxito.");
        txtCodigo.setText("");
        txtNombre.setText("");
        txtTipo.setText("");
        txtPrecio.setText("");
        txtStock.setText("");
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error al guardar los cambios: " + e.getMessage());
    }
} else {
    JOptionPane.showMessageDialog(this, "No se encontró un medicamento con ese código.");
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
String codigo = txtCodigo.getText().trim();

if (codigo.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Ingrese el código del medicamento a eliminar.");
    return;
}

File archivo = new File("medicamentos.txt");
if (!archivo.exists()) {
    JOptionPane.showMessageDialog(this, "El archivo no existe.");
    return;
}

List<String> lineas = new ArrayList<>();
boolean eliminado = false;

try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
    String linea;
    while ((linea = br.readLine()) != null) {
        String[] datos = linea.split(",");
        if (datos.length >= 5 && datos[0].trim().equalsIgnoreCase(codigo)) {
            eliminado = true;
        } else {
            lineas.add(linea);
        }
    }
} catch (IOException e) {
    JOptionPane.showMessageDialog(this, "Error al leer: " + e.getMessage());
    return;
}

if (eliminado) {
    try (PrintWriter pw = new PrintWriter(new FileWriter(archivo, false))) {
        for (String l : lineas) {
            pw.println(l);
        }
        JOptionPane.showMessageDialog(this, "Medicamento eliminado correctamente.");
        txtCodigo.setText("");
        txtNombre.setText("");
        txtTipo.setText("");
        txtPrecio.setText("");
        txtStock.setText("");
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error al reescribir: " + e.getMessage());
    }
} else {
    JOptionPane.showMessageDialog(this, "No se encontró ningún medicamento con ese código.");
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmMedicamentos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
